POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNGFhNzU5MmNlOTEyZWJjYzYzNjM1MyIsImlhdCI6MTY2NTgzOTM4OH0.DwjsgDq9FUphvsIvYQgnWcdHEwmaWCCrajpjXJHUviY

{
  "title": "Cool hats blog",
  "author": "Tyy",
  "url": "www.bird2.gov",
  "likes": 0
}